# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c8199cd0ba9b22ef86b61210daa6ec3c7f091d8d98676dfb516143170b78fea204f86337cd29259895cafe4c5dbd05c7d9e71252bc1b7b1d4487e342c2ef787

test:
  secret_key_base: d9d1e907b4257036823d412f1fdbd4bb0ea677067c602f6a6756903407408fcf80eb11cc45c0ce80010cf3df88a8b29792bb7b5b2081059054245ca2bed1f9f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
